server:
  port: 8080
  host: 0.0.0.0

langchain4j:
  open-ai:
    chat-model:
      enabled: true
      api-key: "demo"
      base-url: "http://langchain4j.dev/demo/openai/v1"
      model-name: "gpt-4o-mini"
