{
 "title": "HAL 9000",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Input Token Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gen_ai_client_token_usage_token_sum{gen_ai_token_type=\"input\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Token Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gen_ai_client_token_usage_token_sum{gen_ai_token_type=\"output\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAL Token Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "gen_ai_client_token_usage_token{gen_ai_operation_name=\"chat\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}